# Generated by Django 6.0.1 on 2026-03-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('botanical', models.CharField(max_length=150)),
                ('seed_type', models.CharField(choices=[('Hybrid', 'Hybrid'), ('Open-Pollinated', 'Open-Pollinated'), ('Heirloom', 'Heirloom')], default='Hybrid', max_length=15)),
                ('continent', models.CharField(max_length=20)),
                ('slug', models.SlugField(help_text='SEO-friendly URLs', max_length=500, null=True)),
            ],
        ),
    ]
