# Generated by Django 6.0.1 on 2026-03-03 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Donor Profiles',
            },
        ),
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uses', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.donorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('botanical', models.CharField(max_length=150)),
                ('seed_type', models.CharField(choices=[('Hybrid', 'Hybrid'), ('Open-Pollinated', 'Open-Pollinated'), ('Heirloom', 'Heirloom')], default='Hybrid', max_length=15)),
                ('continent', models.CharField(max_length=20)),
                ('slug', models.SlugField(help_text='SEO-friendly URLs', max_length=500, null=True)),
                ('donors', models.ManyToManyField(related_name='seeds', to='myapp.donor')),
                ('use', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seeds', to='myapp.use')),
            ],
        ),
    ]
